files:
  - source: /locales/translations/en/**/*.json
    translation: /locales/translations/%locale%/**/%original_file_name%
    update_option: update_as_unapproved
    languages_mapping:
      locale:
        ar: ar
        zh-CN: zh
        zh-TW: zh-tw
        da: da
        fr: fr
        ja: ja
        pt-PT: pt
        ru: ru
        es-ES: es
        en: en-GB-oxendict
        uk: uk
