/* eslint-disable object-curly-spacing */
/*
Similate approximate load on services for the new demo site when visiting a dataset page.
*/
const { graphqlRequest, replaceKeyInVariables } = require('./graphqlRequest');

const exampleKey = '5260693';

function speciesKeyLoad(speciesKey) {
  for (let key of Object.keys(queries)) {
    graphqlRequest(queries[key].query, replaceKeyInVariables(queries[key].variables, exampleKey, speciesKey));
  }
}

const queries = {
  details: {'query': '\n  query TaxonKey($key: ID!) {\n    taxon(key: $key) {\n      key\n      nubKey\n      sourceTaxon {\n        key\n        references\n        datasetKey\n        dataset {\n          title\n        }\n      }\n      issues\n      scientificName\n      canonicalName\n      origin\n      kingdom\n      formattedName(useFallback: true)\n      rank\n      taxonomicStatus\n      publishedIn\n      references\n      datasetKey\n      speciesCount\n      distributionsCount: distributions(limit: 10, offset: 0) {\n        results {\n          taxonKey\n        }\n      }\n      iucnStatus {\n        references\n        distribution {\n          taxonKey\n          threatStatus\n        }\n      }\n      dataset {\n        title\n        key\n        citation {\n          text\n          citationProvidedBySource\n        }\n      }\n      vernacular: vernacularNames(limit: 100, offset: 0) {\n        results {\n          taxonKey\n          language\n          vernacularName\n        }\n      }\n      parents {\n        rank\n        scientificName\n        canonicalName\n        formattedName\n        key\n      }\n      acceptedTaxon {\n        key\n        formattedName\n        scientificName\n      }\n      synonyms(limit: 100, offset: 0) {\n        results {\n          key\n          scientificName\n          canonicalName\n          authorship\n          rank\n          publishedIn\n        }\n      }\n      imagesCount: occurrenceMedia(limit: 0, offset: 0) {\n        count\n      }\n    }\n  }\n', 'variables': {'key': '5260693'}, 'operationName': 'TaxonKey'},
  typeSpecimens: {'query': '\n  query TaxonTypeSpecimens($from: Int, $size: Int, $predicate: Predicate) {\n    occurrenceSearch(predicate: $predicate) {\n      _meta\n      documents(from: $from, size: $size) {\n        from\n        size\n        total\n        results {\n          key\n          taxonKey\n          originalUsageMatch {\n            diagnostics {\n              matchType\n              confidence\n            }\n\n            usage {\n              name\n              key\n            }\n          }\n          classification {\n            usage {\n              name\n              rank\n            }\n          }\n          typeStatus\n          typifiedName\n          catalogNumber\n          recordedBy\n          year\n          country\n          institutionCode\n          collectionCode\n          occurrenceID\n          dataset {\n            key\n            title\n          }\n          extensions {\n            dnaDerivedData\n          }\n        }\n      }\n    }\n  }\n', 'variables': {'predicate': {'type': 'and', 'predicates': [{'type': 'not', 'predicate': {'type': 'equals', 'key': 'typeStatus', 'value': 'NotAType'}}, {'type': 'not', 'predicate': {'type': 'equals', 'key': 'datasetKey', 'value': '55b9ac33-0532-46d3-9796-c4c157f2b097'}}, {'type': 'isNotNull', 'key': 'typeStatus'}, {'type': 'equals', 'key': 'taxonKey', 'value': 5260693}]}, 'size': 50, 'from': 0}, 'operationName': 'TaxonTypeSpecimens'},
  media: {'query': '\n  query TaxonOccurrenceMedia($key: ID!) {\n    taxon(key: $key) {\n      occurrenceMedia(limit: 10, offset: 0) {\n        taxonKey\n        count\n        results {\n          occurrenceKey\n          identifier\n        }\n      }\n    }\n  }\n', 'variables': {'key': 5260693}, 'operationName': 'TaxonOccurrenceMedia'},
  vernacular: {'query': '\n  query TaxonVernacularNames($key: ID!, $limit: Int, $offset: Int) {\n    taxon(key: $key) {\n      vernacularNames(limit: $limit, offset: $offset) {\n        endOfRecords\n        results {\n          vernacularName\n          language\n          sourceTaxonKey\n          sourceTaxon {\n            datasetKey\n          }\n          source\n        }\n      }\n    }\n  }\n', 'variables': {'key': '5260693', 'limit': 200, 'offset': 0}, 'operationName': 'TaxonVernacularNames'},
  treatments: {'query': '\n  query Treatments($key: ID!) {\n    taxon(key: $key) {\n      key\n      rank\n      scientificName\n      treatments {\n        sourceTaxon {\n          key\n          nubKey\n        }\n        publisherKey\n        publisherTitle\n        publisherHomepage\n        datasetTitle\n        datasetKey\n        citation\n        link\n      }\n    }\n  }\n', 'variables': {'key': '5260693'}, 'operationName': 'Treatments'},
  invasives: {'query': '\n  query InvasiveTaxon($key: ID!) {\n    taxon(key: $key) {\n      key\n      invasiveInCountries {\n        country\n        isSubCountry\n        datasetKey\n        dataset\n        scientificName\n        nubKey\n        taxonKey\n        isInvasive\n      }\n    }\n  }\n', 'variables': {'key': '5260693'}, 'operationName': 'InvasiveTaxon'},
  slow: {'query': '\n  query SlowTaxon($key: ID!, $language: String) {\n    taxon(key: $key) {\n      key\n      basionymKey\n      vernacularNames(limit: 1, language: $language) {\n        results {\n          vernacularName\n          source\n        }\n      }\n      combinations {\n        key\n        nameKey\n        acceptedKey\n        canonicalName\n        authorship\n        scientificName\n        formattedName\n        rank\n        taxonomicStatus\n        numDescendants\n      }\n      synonyms(limit: 100, offset: 0) {\n        limit\n        offset\n        endOfRecords\n        results {\n          key\n          nameKey\n          acceptedKey\n          canonicalName\n          authorship\n          scientificName\n          formattedName\n          rank\n          taxonomicStatus\n          numDescendants\n        }\n      }\n      wikiData {\n        source {\n          id\n          url\n        }\n        identifiers {\n          id\n          label\n          description\n          url\n        }\n      }\n    }\n  }\n', 'variables': {'language': 'eng', 'key': '5260693'}, 'operationName': 'SlowTaxon'},
  children: {'query': '\n    query TaxonChildren($key: ID!, $limit: Int, $offset: Int) {\n      taxon(key: $key) {\n        key\n        scientificName\n        numDescendants\n        children(limit: $limit, offset: $offset) {\n          limit\n          endOfRecords\n          offset\n          results {\n            key\n            parentKey\n            numDescendants\n            scientificName\n            canonicalName\n            formattedName(useFallback: true)\n            rank\n          }\n        }\n      }\n    }\n  ', 'variables': {'key': 5260693, 'limit': 50, 'offset': 0}, 'operationName': 'TaxonChildren'}
};

module.exports = {
  speciesKeyLoad
};
